### ISSUE TITLE
Let's work together

### ISSUE THREAD

**Issue by FlorianKoerner** [adorableio/avatars-api-middleware#75]
I really like your adorable avatars and would be happy to create a version for [DiceBear Avatars](https://avatars.dicebear.com/) for it.

DiceBear Avatars works similarly. SVG avatars are created using an identifier. Sprite collections are used, which exist in addition to the library.

I would like to create such a sprite collection for Adorable Avatars, if that's okay with you. For this I would have to redraw the sprites as a vector if you don't have any vectors.

The new repository can also be located in your GitHub organization.

**Comment by rylnd** [comment]
@FlorianKoerner that sounds wonderful! We don't yet have a mechanism to host arbitrary artist's sets, but that's on the roadmap for sure.

Just to clarify what you're suggesting: you'd like to create pixelized versions of our avatars (as a sprite collection), for use in the DiceBear Avatars service?

If so, we unfortunately don't have assets beyond what you see in [src/img](https://github.com/adorableio/avatars-api-middleware/tree/develop/src/img), and those aren't vectorized.

**Comment by FlorianKoerner** [comment]
With your permission, I'd like to vectorize your graphics. Without creating a pixel rated version.

Then both projects could use the graphics. 🎉

**Comment by FlorianKoerner** [comment]
Works the same way. But with separate vector pieces and not with pixel pieces.

**Comment by itsthatguy** [comment]
@FlorianKoerner would you want to get on a call to talk about this? I'd like to know more about your plans, and what best we can do.

**Comment by FlorianKoerner** [comment]
However, I would like to thank you for your interest.

**Comment by luckydonald** [comment]
Funfact, consent to vectorize those still hasn't been given.
