### ISSUE TITLE
Size parameter in URL does not work

### ISSUE THREAD

**Issue by HaakonL** [adorableio/avatars-api-middleware#80]
This works:
https://api.adorable.io/avatars/face/eyes13/nose10/mouth2/00aeff

This does not work:
https://api.adorable.io/avatars/face/eyes13/nose10/mouth2/00aeff/256

According to the tests in the code repository, the size parameter is expected to work.

**Comment by HaakonL** [comment]
Line 49 in integration.js test:

it('can manually compose an image with a custom size', function(done) {
      request.get('/avatars/face/eyes1/nose4/mouth11/bbb/50')
      .expect(200)
      .expect('Content-Type', /image/)
      .parse(parseImage).end(function(err, res) {
        im(res.body).size(function(_, size) {
          expect(size).to.eql({ height: 50, width: 50 });
          done();
        });
      });
    });
  });

**Comment by rylnd** [comment]
Hi @HaakonL, thanks for letting us know! The documentation you're referring to is for the avatars middleware, which distinct from the service living at api.adorable.io. While the documentation is correct, unfortunately the service is not running the latest version of this middleware.

I will update the service tomorrow to amend this discrepancy. In the meantime, you can always [run your own server](https://github.com/adorableio/avatars-api-middleware#how-do-i-use-it).

**Comment by rylnd** [comment]
@HaakonL the newest middleware is now deployed. Please reopen this issue if necessary.
