### ISSUE TITLE
URL's not working all of a sudden, service seems to be down.

### ISSUE THREAD

**Issue by dappvolume** [adorableio/avatars-api-middleware#82]
Hello,

Some URL's are all of a sudden breaking on DappVolume https://dappvolume.com/transactions/eth 

For example: https://api.adorable.io/avatars/32/0x8a9d49a6e9d037843560091fc280b9ff9819e462@adorable.png

 Application error

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. 

```
src="'https://api.adorable.io/avatars/32/' + ethAddress + '@adorable.png'"
```

**Comment by bigtiger** [comment]
Thanks for the heads up. We're looking into this it appears to be a problem related to our CDN provider.

**Comment by bigtiger** [comment]
Added more hardware. This isn't a sustainable long-term fix without billing for folks using this in Production.
