### ISSUE TITLE
Can I use in mobile application?

### ISSUE THREAD

**Issue by baeharam** [adorableio/avatars-api-middleware#89]
I'm implementing chat application by flutter. Can I use this in flutter mobile application?
If so, how can I obtain the way to call API?

**Comment by bigtiger** [comment]
@baeharam 

We host a **development** version of the API here: https://api.adorable.io/avatars/285/abott@adorable.png

With a description of how it's used here: http://avatars.adorable.io/

Please note: This is not intended to support production applications. We highly recommend building a node app that includes this middleware and deploying it on a host you control.

**Comment by baeharam** [comment]
@bigtiger Got it, thanks!
